### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by timoschuett** [AndreasReitberger/RemoteControlRepetierServerProApp#4]
**Describe the bug**
All in all the app is very laggy when pressing buttons.
Second thing is the just partially working webcam.
Third is the Server-IP restriction to numbers only. DynDNS IP's are not useable.

Fourth is the unknown action OR wrong description when deleting printer notifications. It says "...Modell löschen.." instead of "Benachrichtigung löschen". Will it delete die gcdode file or the notification?

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.0.1 (18A393)

Thanks for your work! I am really exited about the potential of this app!

**Comment by AndreasReitberger** [comment]
Hi @timoschuett 
Thank's for sharing your feedback. I'll this with the upcoming update.

The FQDN support for the web address is already implemented and available with the next version.

Thanks!

**Comment by AndreasReitberger** [comment]
Hi @timoschuett 
I'm glad to notify you that following of your mentioned issues are fixed with the next update

- [x] Added support for FQDN support for Repetier Server address
- [x] Fixed wrong dialog message for deleting a message
- [x] We updated all dependencies to the latest version to increase the performance of the app (please verify the performance with the new version and report back).

Only the webcam feature is currently in check. It seems to work fine on my devices here, however I updated the third party library. Maybe this is already the fix. I'll keep you posted on that matter. The update should be available mid / end october.

**Comment by AndreasReitberger** [comment]
Hi @timoschuett 
I hopefully have found the bug causing the WebCam to stop working. Please verify the fix in the upcoming release and let me know if the issue still exists for you.
The update is in the final test phase and should be available soon.
Thanks!

**Comment by AndreasReitberger** [comment]
Issue fixed in latest release. If the problem still occures, please reopen the bug.
